/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function getIncludeFileList(currentDir: string): Array<FileData>
export function walkdirGetIncludeFileList(currentDir: string): Array<FileData>
export interface FileData {
  filename: string
  absolutePath: string
  size: number
  isFile: boolean
}
